project:
  type: website

format:
  html:
    theme: 
      dark: darkly
      light: minty
    # css: styles.css
    toc: true

website:
  open-graph: true
  repo-actions: none
  navbar:
    background: primary
    search: true
    title: "TIL"
  sidebar:
    style: floating

metadata-files: [nbdev.yml, sidebar.yml]